### ISSUE TITLE
Memory usage in mri_synthstrip

### ISSUE THREAD

**Issue by mattcieslak** [freesurfer/freesurfer#1032]
Hi! I noticed that when running `mri_synthstrip` on data with larger voxel sizes (>1mm) there is a large spike in memory use toward the end of the `mri_synthstrip` run. Some crude profiling shows: 

<img width="775" alt="image" src="https://user-images.githubusercontent.com/170026/201225173-88ffa71f-2234-4370-bb8d-61a343cd0417.png">

The two spikes are `mri_synthstrip runs`. The first (at ~14 minutes in) is on a 1mm T1w image and the second is on a 5mm T2w image. Somehow the 5mm image takes over 6GB of memory!

Any idea what might be going on?

**Comment by ahoopes** [comment]
The 6GB is surprising for sure. In general, my guess is that it's just pytorch being aggressive with memory (it has a habit of using more memory than is really needed sometimes). You could try setting the container RAM to 4GB just to see if it still runs. The model is also probably a bit larger than it needs to be. Maybe soon we'll do some tests to see how far we can reduce the network size without sacrificing accuracy.

That being said, the 5mm image probably uses more memory because under the hood, input images are resampled to 1mm resolution. So it you start out with a decent sized 5mm image, then the resampled 1mm could be very large.

What's the shape of your 5mm input?

**Comment by buildqa** [comment]
I'll add that while the system requirements for Freesurfer note "RAM: 8GB for recon, 16GB suggested for viewing graphics". we don't control how installed/3rd party modules allocate and de-allocate memory.   There's already been discussion about updating the minimum RAM requirements for FS - which should not be an issue on modern machines.

**Comment by buildqa** [comment]
Issue above via link is now reported as closed.
