### ISSUE TITLE
Photos are displayed upside down in retrospective correction

### ISSUE THREAD

**Issue by hvgazula** [freesurfer/freesurfer#1039]
https://github.com/freesurfer/freesurfer/blob/584e6d8656975de417786d98eea859580f9b839e/dissection_photo/py_scripts/func_retrospective_correction.py#L48

@rpwang17  Adding
```from PIL import ImageOps```
```self.img_fullres = ImageOps.exif_transpose(self.img_fullres)```

after the above (referenced) line seems to be working in the expected fashion. E put an example at /space/monday/4harsha_and_ruopeng. If you want, I can add more test cases to try. See you soon.

**Comment by rpwang17** [comment]
You mean ‘args' instead of ‘self', right? I added as:

args.img_fullres = ImageOps.exif_transpose(args.img_fullres)


It appears to produce correctedly oriented images.

On Dec 14, 2022, at 7:20 AM, H Gazula ***@***.******@***.***>> wrote:

        External Email - Use Caution



MailScanner has detected a possible fraud attempt from "secure-web.cisco.com<http://secure-web.cisco.com>" claiming to be https://github.com/freesurfer/freesurfer/blob/584e6d8656975de417786d98eea859580f9b839e/dissection_photo/py_scripts/func_retrospective_correction.py#L48

@rpwang17 Adding
from PIL import ImageOps
self.img_fullres = ImageOps.exif_transpose(self.img_fullres)

after the above (referenced) line seems to be working in the expected fashion. E put an example at /space/monday/4harsha_and_ruopeng. If you want, I can add more test cases to try. See you soon.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/freesurfer/freesurfer/issues/1039", "url": "https://github.com/freesurfer/freesurfer/issues/1039", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by hvgazula** [comment]
Yep, you are right. I was a bit careless when pasting the code from my end.
