### ISSUE TITLE
Synthstrip docker and CIFS file system

### ISSUE THREAD

**Issue by jrdalenberg** [freesurfer/freesurfer#1179]
Hey all, 

I was trying the synthstrip docker wrapper as described at: https://surfer.nmr.mgh.harvard.edu/docs/synthstrip/

My files are on a CIFS drive and this causes some weird behavior with rights. Although my user account is allowed to run docker without sudo rights, the script crashes with a file not found error. 

`synthstrip-docker -i in.nii.gz -o out.nii.gz` does not work but `sudo synthstrip-docker -i in.nii.gz -o out.nii.gz` does. 

Any way to circumvent this? I do not want to use sudo in my preprocessing scripts. 

I have no other right-issues with other docker containers such as fmriprep while using the same drive as input and output.

**Comment by mu40** [comment]
Hi Jelle! Does your unprivileged user account have read/write permissions to the CIFS drive, and are you explicitly setting this user with `-u` or `--user` for `fmriprep-docker`? If not, then the fmriprep container may be running as root. This would be analogous to `sudo synthstrip-docker` because the SynthStrip wrapper executes the SynthStrip container as the user running this script.

**Comment by jrdalenberg** [comment]
Thanks for the quick reply @mu40. We found our issue at https://github.com/freesurfer/freesurfer/blob/dev/mri_synthstrip/synthstrip-docker#L52. 

The docker image used the wrong group ID. I manually corrected it in the script for our system.
