### ISSUE TITLE
FreeSurfer on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by costantinoai** [freesurfer/freesurfer#1203]
First of all, thanks for developing and maintaining this awesome tool.

I upgraded my Ubuntu system to 24.04 LTS and, after the upgrade, FreeSurfer was deleted. I tried re-installing again, but the installation returned a version error for the libc6 package. Considering this is an important package, I assume it would not be safe to downgrade the existing installation to meet the FreeSurfer requirements, and that perhaps FS is not yet compatible with 24.04 LTS.

Is there any workaround to this, or is there any release on the horizon to ensure compatibility with latest Ubuntu LTS version?

Thanks!
Andrea

**Comment by buildqa** [comment]
We currently do not support Ubuntu 24 - which may use newer compilers and/.or a newer version of glibc compared to Ubuntu 22.   If binary backwards compatibility does not work, the Ubuntu linux 24 install tools may not allow the Ubuntu 22 .deb freesurfer package.   Please keep in mind that Ubuntu 22.04 LTS was released in Apr 2022 and is not end of life'd until Apr 2027.   Freesurfer users may not be anxious to update to the latest OS versions because of the caveat we list at the bottom of the freesurfer version 7 release page, https://surfer.nmr.mgh.harvard.edu/fswiki/rel7downloads.  I think we will eventually support Ubuntu24, but I don't have a timeframe.  We will keep an eye out for users requesting it.

**Comment by tiborauer** [comment]
I'd like to upvote supporting Ubuntu 24.04 LTS.

**Comment by buildqa** [comment]
You will miss announcements if you don't subscribe to the freesurfer mailing list, e.g., info was posted last week about how to try a freesurfer ubuntu24 development build.

**Comment by tiborauer** [comment]
Thanks, @buildqa! Can I see past messages if I subscribe now? The archive only displays messages before August 2025.

**Comment by buildqa** [comment]
I don't know the details if how the online mail archive is updated, but here is the text of that message,

```
Please note *development* (post 8.1.0) builds are available for Rocky 9 and Ubuntu 24 Linux (along with the same build for other platforms) under,

> https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/dev_20260102/

Development builds are not releases and so they are potentially unstable and not fully tested to the point where they are suitable for long term work.   We would be interested in feedback from running known to be good recon-all, etc. command line sequences using the Rocky 9 and Ubuntu 24 builds on their respective OS's.

Caveat from the Freesurfer release page,

> Important Note: When processing a group of subjects for your study, it is essential to process all your subjects with the same version of FreeSurfer, on the same OS platform and vendor, and for safety, even the same version of the OS. While we continue to work to ensure that results match across platforms, there are none-the-less system-level libraries that are OS dependent. An exception to this rule is that you may view and edit files across any platform or version, and run some post-processing tools (outside the recon-all stream) if you check with us first (for instance you may run the longitudinal processing with newer versions).
```
