### ISSUE TITLE
Starting Freeview

### ISSUE THREAD

**Issue by melrobin** [freesurfer/freesurfer#264]
### Platform details:

- FreeSurfer version: latest GitHub version
- Operating system name and version:  Fedora 25

### Summary
I am able to build FreeSurfer from source, but when starting freeview I get the following error:
[melrobin@scorpion ~]$ freeview
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".  

Reinstalling the application may fix this problem.
Abort (core dumped)

There should be a platforms directory somewhere, but it does not appear.
### Actual behavior
Error message as above
### Expected behavior
GUI to appear

**Comment by melrobin** [comment]
Trying to do some troubleshooting:
[melrobin@scorpion ~]$ ldd $FREESURFER_HOME/bin/freeview.bin | grep xcb
        libxcb.so.1 => /lib64/libxcb.so.1 (0x00007efe4af38000)

So the library libxcb.so is there, but I thought libqxcb.so is needed

**Comment by melrobin** [comment]
The Qt in the centos_x86-64 package directory does not have a plugins directory, but my system Qt does.

**Comment by melrobin** [comment]
I was able to build Qt 5.6.2 and move the plugins directory in the qt subdirectory of packages and modify QT_QPA_PLATFORM_PLUGIN_PATH environment variable and was able to launch freeview.bin.  I'll try additional experiments, but it seems that plugins needs to be distributed in centos6-x86_64-packages

**Comment by buildqa** [comment]
You could also try the following to check if there are any other missing lib references,

$ ldd $FREESURFER_HOME/bin/freeview.bin | grep "not found"

Since ldd calls the loader, then environment variables like LD_LIBRARY_PATH will affect the result, but QT specific environment variables will not, I believe.  (I'm not suggesting you set LD_LIBRARY_PATH though).  

If you are expecting to get your qt5 libs etc. from the system, then I would check that the package qt5-qtbase.x86_64 is installed, and maybe qt5-qtbase-devel.x86_64 (or that is what I recall from CentOS).

You can also try to see where the qtlibs are coming from via
$ ldd $FREESURFER_HOME/bin/freeview.bin | grep -i libqt

**Comment by melrobin** [comment]
Check out the contents of the qt under the packages tarball.  It does not contain a plugins directory and so the directory will not contain libqxcb.so.

**Comment by mpantoja314** [comment]
I have the same problem, I can compile freesurfer from scratch and everything seam to be working but I can't run FreeView. Same problem with "xcb"
melrobin can you please give some more details about how you did solve it:
"I was able to build Qt 5.6.2 and move the plugins directory in the qt subdirectory of packages and modify QT_QPA_PLATFORM_PLUGIN_PATH environment variable and was able to launch freeview.bin."

**Comment by buildqa** [comment]
If you look at freeview, you will see it is a csh script that sets the environment and then calls freeview.bin.  For the Qt environment it sources the script $FREESURFER_HOME/bin/qt_setup.  If you look at this script you will see that unless you set the environment variable FS_QT_HOME to the parent path of the ./bin, ./lib subdirs of your own Qt distribution, e.g., the one that you built, then it is going to 
look for $FREESURFER_HOME/lib/qt.  It then eventually adds where it can find the Qt libs to the library search path, LD_LIBRARY_PATH.  For xcb libs, my $FREESURFER_HOME/lib/qt path looks like it ends up ponting to these *xcb* libs,
libQt5XcbQpa.la
libQt5XcbQpa.prl
libQt5XcbQpa.so@
libQt5XcbQpa.so.5@
libQt5XcbQpa.so.5.6@

So you could try setting FS_QT_HOME so that $FS_QT_HOME/lib is the directory with your Qt libs (and $FS_QT_HOME/bin is the path to Qt binaries).   If this variable is set then not only will the path it contains be added to LD_LIBRARY_PATH, but it will also be used to set QTLIBPATH to find libs.

**Comment by melrobin** [comment]
The problem that I had was the plugins directory.  It was missing from the packages distribution.  After downloading the tarball, decompressing it, extracting the plugins directory and making sure that the plugins environment variable pointed to the proper directory I was able to launch Freeview.

**Comment by mpantoja314** [comment]
I did get the plugin folder from:
/usr/lib/x86.../Qt5/plugins
I did copy this folder to the freesurfer/packages
I did also update the QT_QPA_PLATFORM_PLUGIN_PATH= to the freesurfer/pagages.qt/pluging
But I still get the could not load pluging xcb

When you say you downloaded the tar ball you mean:
apt-get source libxcb
sudo apt-get build-dep libxcb
cd libxcb-1.11.1/
dpkg-buildpackage -us -uc
or is something else?

Thanks so much for your help. I did try to change the FS_QT_HOME and is doesn't work either

**Comment by melrobin** [comment]
Check that the versions of Qt match.  In fact, I used Qt 5.6 because it matched the version of Qt used in the centos packages tarball.

**Comment by mpantoja314** [comment]
Thanks to both of you. I now have a fully functional freesurfer with gpu support (Cuda 9.0) and freeview is also working fine

**Comment by m-reuter** [comment]
Before closing this issue, we need to add QT plugins required by FreeView to the plugin dir in the centos packages tarball. Together with the fix in qt_setup #444 we should be all set then.

**Comment by ahoopes** [comment]
The xcbglintegrations plugin has been added to the prebuilt packages tar under `qt/current/plugins`
