### ISSUE TITLE
Freesurfer packages needs more files to do a recon-all

### ISSUE THREAD

**Issue by emtpgeek** [freesurfer/freesurfer#499]
I have had to copy the following files from the old centos packages to get recon-all to run

/Bevin

    for F in \
        correct_field \
        evaluate_field \
        make_template \
        minccalc \
        mincinfo \
        mincmath \
        mincresample \
        mincstats \
        nu_correct \
        nu_estimate_np_and_em \
        nu_evaluate \
        resample_labels \
        sharpen_hist \
        sharpen_volume \
        spline_smooth \
        volume_hist \
        volume_stats \
        
    do
        cp /home/rheticus/centos6-x86_64-packages/mni/1.5/bin/$F ~/freesurfer-packages/minc/1.5/bin/
    done
    chmod 755 ~/freesurfer-packages/minc/1.5/bin/*

    mkdir    ~/freesurfer-packages/minc/1.5/lib/perl5
    cp -r ~/centos6-x86_64-packages/mni/1.5/lib/perl5/5.8.5 \
             ~/freesurfer-packages/minc/1.5/lib/perl5/5.8.5

**Comment by ahoopes** [comment]
I've added mni 1.5 to the [prebuilt packages tarballs](https://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt) and added a step in CMakeLists.txt (https://github.com/freesurfer/freesurfer/commit/ee461f048a2d442035cde41e0957d9fc3c4b7c6c) so that `freesurfer/mni` gets linked to either the `MNI_DIR` env var or to `${FS_PACKAGES_DIR}/mni/current` during install
