### ISSUE TITLE
template to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#803]
Hello, I would like to ask you a question. After processing with freesurfer (recon all), there are too many vertices, there are more than 130,000. I see a paper that is registered to fsaverage5 (its vertices are only 10000+) to reduce The number of vertices, how is this registration operation realized?

**Comment by ahoopes** [comment]
Nonlinear surface registration is achieved through spherical registration (`mris_register`) and mesh resampling can be done with `mri_surf2surf`. The overview of this process is described in the [SurfaceRegAndTemplates](https://surfer.nmr.mgh.harvard.edu/fswiki/SurfaceRegAndTemplates) wiki page.

Although, I'm closing this thread since this is a question that should be posted on the [FS help list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport). We reserve github issues for tracking software bugs.
