### ISSUE TITLE
Question about .annot file

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#820]
hello, After I updated the vertex_label of rh.aparc.a2009s.annot with an algorithm, now I want to replace the vertex_label in the .annot with the updated vertex_label, mainly to see the effect of the segmentation, do you know what to do ?

**Comment by ahoopes** [comment]
Hi, I'm not entirely sure what you are asking, but if you're looking to manually edit annotations, you can edit values directly in tksurfer (FS 6). This functionality hasn't been added to freeview yet. If you're looking to script these updates, you will have to use the FS matlab library to make edits (see `read_annotation.m` and `write_annotation.m`). After you've modified the labels, you can run the `mri_aparc2aseg` commands from the `recon-all.cmd` log to project the annot to the segmentation volumes. Once again, please post this type of question to the [FS mailing list](https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport) instead of the github issues page. Thanks

**Comment by tanjia123456** [comment]
Hello, I sent an email a week ago, but no one responded.
In fact, my purpose is very simple. For fsaverage5, I got the updated vertex_label_index（10242）, and I want to replace it with the previous value of vertex_label_index in the rh.aparc.a2009s.annot file. Then load the updated rh.aparc.a2009s.annot through freeview to visualize the effect of my algorithm prediction.
I wonder if I describe it clearly?
So do you know how to solve my problem?
Looking forward to your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freesurfer/freesurfer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 晚上9:24
收件人:&nbsp;"freesurfer/freesurfer"<freesurfer@noreply.github.com&gt;;
抄送:&nbsp;"1248742467"<1248742467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [freesurfer/freesurfer] Question about .annot file (#820)





 
Hi, I'm not entirely sure what you are asking, but if you're looking to manually edit annotations, you can edit values directly in tksurfer (FS 6). This functionality hasn't been added to freeview yet. If you're looking to script these updates, you will have to use the FS matlab library to make edits (see read_annotation.m and write_annotation.m). After you've modified the labels, you can run the mri_aparc2aseg commands from the recon-all.cmd log to project the annot to the segmentation volumes. Once again, please post this type of question to the FS mailing list instead of the github issues page. Thanks

**Comment by ahoopes** [comment]
It looks like someone did respond to your issue on the mailing list. Regardless, my above response should answer your question.
